{
 "title": "Weather",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius", "label": "temperature" }
   ],
   "targets": [
    { "expr": "weather_temp_kuchyne", "legendFormat": "kuchyne" },
    { "expr": "weather_temp_terasa", "legendFormat": "terasa" }
   ]
  },
  {
   "title": "Barometric pressure at sea level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pressurehpa", "label": "hPa" }
   ],
   "targets": [
    { "expr": "pressure_sea_level_hpa" }
   ]
  },
  {
   "title": "Outside temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "weather_temp_terasa" }
   ]
  },
  {
   "title": "Inside temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "weather_temp_kuchyne" }
   ]
  }
 ]
}